package com.amazonaws.models.nosql;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

import java.util.List;
import java.util.Map;
import java.util.Set;

@DynamoDBTable(tableName = "myshuttleapp-mobilehub-389102477-ReportDelay")

public class ReportDO {
    private String _shuttleId;
    private String _reportTime;
    private String _reportedBy;
    private String _entryId;
    private String _stopId;


    @DynamoDBAttribute(attributeName = "shuttleId")
    public String getShuttleId() {
        return _shuttleId;
    }

    public void setShuttleId(final String _shuttleId) {
        this._shuttleId = _shuttleId;
    }

    @DynamoDBAttribute(attributeName = "stopId")
    public String getStopId() {
        return _stopId;
    }
    public void setStopId(final String _stopId) {
        this._stopId = _stopId;
    }

    @DynamoDBAttribute(attributeName = "reportTime")
    public String getReportTime() {
        return _reportTime;
    }
    public void setReportTime(final String _reportTime) {
        this._reportTime = _reportTime;
    }

    @DynamoDBAttribute(attributeName = "reportedBy")
    public String getReportedBy() {
        return _reportedBy;
    }
    public void setReportedBy(final String _reportedBy) {
        this._reportedBy = _reportedBy;
    }



    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "entryId")
    @DynamoDBAttribute(attributeName = "entryId")
    public String getEntryId() {
        return _entryId;
    }

    public void setEntryId(String _entryId) {
        this._entryId = _entryId;
    }
}
