package com.amazonaws.models.nosql;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

import java.util.List;
import java.util.Map;
import java.util.Set;

@DynamoDBTable(tableName = "myshuttleapp-mobilehub-389102477-ShuttleEntry")

public class ShuttleDO {
    private String _shuttleId;
    private String _reportTime;
    private String _reporteBy;
    private String _shuttleLat;
    private String _shuttleLatestStop;
    private String _shuttleLon;
    private String _entryId;


    @DynamoDBAttribute(attributeName = "shuttleId")
    public String getShuttleId() {
        return _shuttleId;
    }

    public void setShuttleId(final String _shuttleId) {
        this._shuttleId = _shuttleId;
    }

    @DynamoDBRangeKey(attributeName = "reportTime")
    @DynamoDBAttribute(attributeName = "reportTime")
    public String getReportTime() {
        return _reportTime;
    }

    public void setReportTime(final String _reportTime) {
        this._reportTime = _reportTime;
    }
    @DynamoDBAttribute(attributeName = "reporteBy")
    public String getReporteBy() {
        return _reporteBy;
    }

    public void setReporteBy(final String _reporteBy) {
        this._reporteBy = _reporteBy;
    }
    @DynamoDBAttribute(attributeName = "shuttleLat")
    public String getShuttleLat() {
        return _shuttleLat;
    }

    public void setShuttleLat(final String _shuttleLat) {
        this._shuttleLat = _shuttleLat;
    }
    @DynamoDBAttribute(attributeName = "shuttleLatestStop")
    public String getShuttleLatestStop() {
        return _shuttleLatestStop;
    }

    public void setShuttleLatestStop(final String _shuttleLatestStop) {
        this._shuttleLatestStop = _shuttleLatestStop;
    }
    @DynamoDBAttribute(attributeName = "shuttleLon")
    public String getShuttleLon() {
        return _shuttleLon;
    }

    public void setShuttleLon(final String _shuttleLon) {
        this._shuttleLon = _shuttleLon;
    }

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "entryId")
    @DynamoDBAttribute(attributeName = "entryId")
    public String getEntryId() {
        return _entryId;
    }

    public void setEntryId(String _entryId) {
        this._entryId = _entryId;
    }
}
