package com.amazonaws.mobile.api;

//
//  CloudLogicAPIFactory.java
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.17
//

/**
 * Produces instances of Cloud Logic API configuration.
 */
public class CloudLogicAPIFactory {

    private CloudLogicAPIFactory() {}

    /**
     * Gets the configured micro-service instances.
     * @return
     */
    public static CloudLogicAPIConfiguration[] getAPIs() {
        final CloudLogicAPIConfiguration[] apis = new CloudLogicAPIConfiguration[] {
                new CloudLogicAPIConfiguration("reportShttle",
                                              "To set the location of the shuttle by user reporting",
                                              "https://ie740b5ibc.execute-api.us-west-1.amazonaws.com/Development",
                                              new String[] {
                                                  "/items",
                                                  "/items/123",
                                              },
                                              com.amazonaws.mobile.api.idie740b5ibc.ReportShttleMobileHubClient.class),
        };

        return apis;
    }
}
